package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * @author Hiro *
 */
public class Login extends javax.swing.JFrame {

    private Connection conn;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        conn = Koneksi.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        loginTxt = new javax.swing.JLabel();
        nmLabel = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        pwdLabel = new javax.swing.JLabel();
        tfPwd = new javax.swing.JPasswordField();
        signinBtn = new javax.swing.JLabel();
        txtBottom = new javax.swing.JLabel();
        bgLogin = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arcadia Game Store");
        setSize(new java.awt.Dimension(1200, 675));

        LoginPanel.setPreferredSize(new java.awt.Dimension(1200, 675));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Login txt.png"))); // NOI18N
        loginTxt.setFocusable(false);
        LoginPanel.add(loginTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 160, 92, 41));

        nmLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Userrname.png"))); // NOI18N
        nmLabel.setText("jLabel1");
        nmLabel.setPreferredSize(new java.awt.Dimension(253, 63));
        LoginPanel.add(nmLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 246, 254, 64));

        tfName.setBackground(new java.awt.Color(0, 0, 0, 0));
        tfName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setBorder(null);
        LoginPanel.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 267, 242, 43));

        pwdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Password.png"))); // NOI18N
        pwdLabel.setText("jLabel1");
        pwdLabel.setPreferredSize(new java.awt.Dimension(253, 64));
        LoginPanel.add(pwdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 331, 254, 65));

        tfPwd.setBackground(new java.awt.Color(0, 0, 0, 0));
        tfPwd.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tfPwd.setForeground(new java.awt.Color(255, 255, 255));
        tfPwd.setBorder(null);
        LoginPanel.add(tfPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 352, 242, 43));

        signinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Sign In.png"))); // NOI18N
        signinBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signinBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signinBtnMouseExited(evt);
            }
        });
        LoginPanel.add(signinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 420, 256, 47));

        txtBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Don't Have.png"))); // NOI18N
        txtBottom.setText("jLabel1");
        txtBottom.setPreferredSize(new java.awt.Dimension(228, 14));
        txtBottom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBottomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBottomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBottomMouseExited(evt);
            }
        });
        LoginPanel.add(txtBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 560, 229, 15));

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Background Panel.png"))); // NOI18N
        LoginPanel.add(bgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 83, 354, 527));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Login.png"))); // NOI18N
        LoginPanel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signinBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinBtnMouseClicked
        signinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Sign In.png")));
        // Mendapatkan input dari JTextField
        String username = tfName.getText();
        String password = tfPwd.getText();
        String query = "SELECT * FROM user WHERE username=? AND password=?";
        try (PreparedStatement preparedStatement = conn.prepareStatement(query)) {
            preparedStatement.setString(1, username);
            preparedStatement.setString(2, password);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                UserSession.setLoggedInUsername(username);
                Menu menu = new Menu();
                menu.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Username atau Password anda salah" + "\nSilahkan isi kembali", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database not Connected", "Information", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_signinBtnMouseClicked

    private void signinBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinBtnMouseEntered
        signinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Sign In Hover.png")));
    }//GEN-LAST:event_signinBtnMouseEntered

    private void signinBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinBtnMouseExited
        signinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Sign In.png")));
    }//GEN-LAST:event_signinBtnMouseExited

    private void txtBottomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBottomMouseClicked
        txtBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Don't Have.png")));
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtBottomMouseClicked

    private void txtBottomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBottomMouseEntered
        txtBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Don't Have Hover.png")));
    }//GEN-LAST:event_txtBottomMouseEntered

    private void txtBottomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBottomMouseExited
        txtBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Don't Have.png")));
    }//GEN-LAST:event_txtBottomMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel bgLogin;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JLabel nmLabel;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JLabel signinBtn;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPwd;
    private javax.swing.JLabel txtBottom;
    // End of variables declaration//GEN-END:variables
}
