/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.JPanel;

/**
 *
 * @author Hiro
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JLabel();
        aboutBtn = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JLabel();
        bgLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arcadia Game Store");
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 675));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setMinimumSize(new java.awt.Dimension(1200, 675));
        homePanel.setPreferredSize(new java.awt.Dimension(1200, 675));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Login.png"))); // NOI18N
        loginBtn.setLabelFor(loginBtn);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBtn.setPreferredSize(new java.awt.Dimension(216, 70));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        homePanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 452, 137, 47));

        aboutBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/About.png"))); // NOI18N
        aboutBtn.setLabelFor(aboutBtn);
        aboutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutBtnMouseExited(evt);
            }
        });
        homePanel.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 452, 137, 47));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/Main Menu.png"))); // NOI18N
        homePanel.add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(homePanel, "card2");

        aboutPanel.setPreferredSize(new java.awt.Dimension(1200, 675));
        aboutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Home.png"))); // NOI18N
        homeBtn.setLabelFor(loginBtn);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homeBtn.setPreferredSize(new java.awt.Dimension(216, 70));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        aboutPanel.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 565, 137, 47));

        bgLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui/About.png"))); // NOI18N
        bgLabel2.setPreferredSize(new java.awt.Dimension(1200, 675));
        aboutPanel.add(bgLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(aboutPanel, "card3");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Login Hover.png")));
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Login.png")));
    }//GEN-LAST:event_loginBtnMouseExited

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Login.png")));
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginBtnMouseClicked

    private void aboutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutBtnMouseClicked
        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/About.png")));
        switchPanel(aboutPanel);
    }//GEN-LAST:event_aboutBtnMouseClicked

    private void aboutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutBtnMouseEntered
        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/About Hover.png")));
    }//GEN-LAST:event_aboutBtnMouseEntered

    private void aboutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutBtnMouseExited
        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/About.png")));
    }//GEN-LAST:event_aboutBtnMouseExited

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Home.png")));
        switchPanel(homePanel);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Home Hover.png")));
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/Home.png")));
    }//GEN-LAST:event_homeBtnMouseExited

    private void switchPanel(JPanel newPanel) {
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(newPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutBtn;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel bgLabel2;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
